// File: src/store/types.js

// Auth Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const AUTH_STATE_CHECK = 'AUTH_STATE_CHECK';

// Sensor Types
export const FETCH_SENSORS_REQUEST = 'FETCH_SENSORS_REQUEST';
export const FETCH_SENSORS_SUCCESS = 'FETCH_SENSORS_SUCCESS';
export const FETCH_SENSORS_FAILURE = 'FETCH_SENSORS_FAILURE';
export const UPDATE_FOOD_LEVEL = 'UPDATE_FOOD_LEVEL';
export const UPDATE_WATER_LEVEL = 'UPDATE_WATER_LEVEL';
export const UPDATE_TEMPERATURE = 'UPDATE_TEMPERATURE';
export const UPDATE_HUMIDITY = 'UPDATE_HUMIDITY';

// Control Types
export const DISPENSE_FOOD_REQUEST = 'DISPENSE_FOOD_REQUEST';
export const DISPENSE_FOOD_SUCCESS = 'DISPENSE_FOOD_SUCCESS';
export const DISPENSE_FOOD_FAILURE = 'DISPENSE_FOOD_FAILURE';
export const DISPENSE_WATER_REQUEST = 'DISPENSE_WATER_REQUEST';
export const DISPENSE_WATER_SUCCESS = 'DISPENSE_WATER_SUCCESS';
export const DISPENSE_WATER_FAILURE = 'DISPENSE_WATER_FAILURE';
export const SET_TEMPERATURE_REQUEST = 'SET_TEMPERATURE_REQUEST';
export const SET_TEMPERATURE_SUCCESS = 'SET_TEMPERATURE_SUCCESS';
export const SET_TEMPERATURE_FAILURE = 'SET_TEMPERATURE_FAILURE';

// Schedule Types
export const FETCH_SCHEDULES_REQUEST = 'FETCH_SCHEDULES_REQUEST';
export const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS';
export const FETCH_SCHEDULES_FAILURE = 'FETCH_SCHEDULES_FAILURE';
export const CREATE_SCHEDULE_REQUEST = 'CREATE_SCHEDULE_REQUEST';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const CREATE_SCHEDULE_FAILURE = 'CREATE_SCHEDULE_FAILURE';
export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_FAILURE = 'UPDATE_SCHEDULE_FAILURE';
export const DELETE_SCHEDULE_REQUEST = 'DELETE_SCHEDULE_REQUEST';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAILURE = 'DELETE_SCHEDULE_FAILURE';
export const GET_SCHEDULES_REQUEST = 'GET_SCHEDULES_REQUEST';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_FAILURE = 'GET_SCHEDULES_FAILURE';
export const TOGGLE_SCHEDULE_REQUEST = 'TOGGLE_SCHEDULE_REQUEST';
export const TOGGLE_SCHEDULE_SUCCESS = 'TOGGLE_SCHEDULE_SUCCESS';
export const TOGGLE_SCHEDULE_FAILURE = 'TOGGLE_SCHEDULE_FAILURE';

// Notification Types
export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

//Setting Types
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

//History Types
export const FETCH_SENSOR_HISTORY_REQUEST = 'FETCH_SENSOR_HISTORY_REQUEST';
export const FETCH_SENSOR_HISTORY_SUCCESS = 'FETCH_SENSOR_HISTORY_SUCCESS';
export const FETCH_SENSOR_HISTORY_FAILURE = 'FETCH_SENSOR_HISTORY_FAILURE';